### ISSUE TITLE
!permit @user

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#101]
This would be much more elegant than using `!togglelinks` every time someone wants / needs to post a link in a channel. It would essentially permit the user tagged to post a link within the channel that the command is given for `X` amount of minutes. @ThePjpollie I'm not sure the amount that would be good here. I feel 5 minutes would be ideal and it automatically disallow them from posting links again after the 5 minutes (unless permitted again of course). This would need to be logged to `#ac-logs` as well with the same style of embed as `!togglelinks` except the first line would read `@user (discordID) has been permitted at` instead of `Link protection disabled/enabled at`

If 5 minutes is not possible, then what is the shortest time that you think would be allowed/good? @ThePjpollie

**Comment by ThePjpollie** [comment]
This should definitely be possible, looking in it right away :)
