### ISSUE TITLE
!get title bug

### ISSUE THREAD

**Issue by ThePjpollie** [HaydenMeloche/AlphaConsoleBot#104]
Requesting the title myself provided me this in DM:
![discord_2018-01-21_17-51-59](https://user-images.githubusercontent.com/12276548/35196576-4a090a22-fed4-11e7-8407-bd7ec507169b.png)

*If not clear: the 7 should not be there*

**Comment by HaydenMeloche** [comment]
Looks to be a bug. I'll look into it when I have time

**Comment by HaydenMeloche** [comment]
@ThePjpollie How did you reproduce this bug?
https://i.imgur.com/UGtkpLv.png

**Comment by ThePjpollie** [comment]
Doing !get title in #set-title

**Comment by ThePjpollie** [comment]
![discord_2018-01-24_17-22-41](https://user-images.githubusercontent.com/12276548/35343535-3240a7ac-012b-11e8-8b85-cc50d2790fbb.png)

Just tested it. Just through `!get title` in `#set-title`
I also see it's saying Cycling Colours whilst it's only RLCS blue

**Comment by HaydenMeloche** [comment]
AH I got it now. I was doing `checkdb`

**Comment by HaydenMeloche** [comment]
should be fixed in b124d35
