### ISSUE TITLE
Automated Spam Protection

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#105]
Currently the spam protection seems jumpy at times. It has repeatedly muted people for seemingly no reason, could be a sensitivity issue. Carsillas suggested having it relaxed for members with roles but it has acted upon regular users as well.

Also, I know I've said this prior to you @ThePjpollie but having the deletion of messages handled differently might work better as well. If it could be possible to have the exact amount of messages that triggered the spam protection deleted rather than searching the channel for X amount of messages in the channel by that person.

**Comment by HaydenMeloche** [comment]
I updated its filter we'll see how this goes

**Comment by ThePjpollie** [comment]
I think we can close this? Since there hasn't been much complains about it.
Closing for now, reopen in case you need to :)
