### ISSUE TITLE
Time dependent command enhancements

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#116]
Commands that are dependent on time (Mute, Giveaways eventually, etc.) should have their time determined by `s` `m` `h` `d` being `second` `minute` `hour` `day` respectively. If no time is provided, it should default to hours as it does currently.

**Comment by coledeb** [comment]
As an example command: `!mute @Cole#0001 10m Being stupid.` would mute me for 10 minutes.

**Comment by HaydenMeloche** [comment]
honestly don't see the point :/

At least for muting. 10 minute mute is pretty useless.

**Comment by coledeb** [comment]
Its not as much about a point as thats the standard for a mute function in a bot.

**Comment by xNameless69** [comment]
https://github.com/HaydenMeloche/AlphaConsoleBot/pull/133

Doesn't have to be merged, but the option is there if wanted. Default can be changed by changing 
`var timeunitDisplay = "hours";` to either days, hours, minutes or seconds
