### ISSUE TITLE
Title update/override still failing

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#118]
There are still cases where a user cannot update their title color and I cannot override it to be the correct color. For example, `@chebi#5026`'s current colors are `1::7` and they cannot update it to just `7` nor can I override it to be `7`. The bot returns "User @chebi updated successfully." but their color is `not` updated.

**Comment by HaydenMeloche** [comment]
Fixed override issue in  de982fa37e1bb20f87f210a5465c13c4c7e48575
Not exactly sure the problem for the user himself setting it yet

**Comment by coledeb** [comment]
Honestly the override is the main one that needed to be fixed so that there is a fallback either way, thank you for that.

**Comment by HaydenMeloche** [comment]
Have we had problems recently with this?
Am I good to close? @coledeb

**Comment by coledeb** [comment]
Yeah I haven't had any other issues or had other reports from users. For some reason `designer` still triggers the blacklist but that's been an issue as long as we have had the blacklist and can be dealt with later / in a separate issue.
