### ISSUE TITLE
Pingsock emoji ID update needed

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#121]
When tagging the bot, it is supposed to respond to the tag by reacting with a `:pingsock:`.  The emoji ID of `:pingsock:` is still the ID from the beta server rather than the main server so the reaction fails. IMPORTANT BUG PLS FIX

**Comment by nitrog0d** [comment]
"IMPORTANT BUG PLS FIX" die pls

**Comment by HaydenMeloche** [comment]
When discord leaks to github

**Comment by Vezqi** [comment]
When this github leaks to my email for some reason :barbocide:

**Comment by xNameless69** [comment]
Fixed in https://github.com/HaydenMeloche/AlphaConsoleBot/pull/126
