### ISSUE TITLE
Welcome message for Legacy

### ISSUE THREAD

**Issue by HaydenMeloche** [HaydenMeloche/AlphaConsoleBot#122]
When someone gets the twitch role they get a message saying welcome and the additional features that twitch gives them.

Would like to implement the same thing for when someone gets the legacy role.

**Comment by xNameless69** [comment]
pls test https://github.com/HaydenMeloche/AlphaConsoleBot/pull/127

**Comment by Vezqi** [comment]
Looks good 👍
