### ISSUE TITLE
!command <user id> Feature.

### ISSUE THREAD

**Issue by Vezqi** [HaydenMeloche/AlphaConsoleBot#140]
So we have a feature that does `!command <mention>` that mentions a user with the command, but doing this also gives them 2 pings. Anyway we could implement it, so that we can do `!command <user id>` and `!command <mention>`, to avoid 2 pings?

**Comment by HaydenMeloche** [comment]
I don't see the problem of pinging them twice tbh

**Comment by Vezqi** [comment]
There isn't an issue with it, it's just seems annoying to get pinged twice. /shrug

**Comment by HaydenMeloche** [comment]
We can still implement this @Vezqi more options never hurt anyone
