### ISSUE TITLE
Double line title causes Runtime error

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#141]
If a user sets a title that takes up two lines in discord (requiring them to hold shift and press enter to go to the second line), then every player they come against that uses AlphaConsole crashes with a runtime error:
https://cdn.discordapp.com/attachments/278336241114677258/414142126452899842/unknown.png

This doesn't crash the game if they hit X, but this is still a very high priority bug.

**Comment by coledeb** [comment]
Nvm barb made a more detailed issue

**Comment by HaydenMeloche** [comment]
lol
