### ISSUE TITLE
Cannot set 4 or 5 titles in one title with ::

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#144]
Currently the bot says that 5 titles is the maximum amount that a user is allowed to set, but it does not allow you to set 5 or even 4 titles joined by `::`.  The maximum that is allowed to be set is 3.

**Comment by xNameless69** [comment]
#149

**Comment by coledeb** [comment]
@HaydenMeloche has this been fixed in the live bot? Can close this issue if it has.
