### ISSUE TITLE
"Mod Mail" functionality

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#152]
This would probably be done with a separate bot, just writing it down here to put forward the initial concept.  This could be used from everything to concerns forwarded to the moderator to possibly even transforming our help channel into a case-based user support system.  The details that I will write after this will be written for the specific "mod mail" case but obviously can be modified based on our needs.

The bot would be open to DMs that are handled on a case by case basis (in time-based order of receiving the DMs).  The bot upon receiving a DM will open the case in a channel within the server (tagging the moderator role in that role upon opening the case). The bot would transcribe every message that the user sends to the bot's DM into the channel, and would respond to the user with the transcription of the messages sent in the channel. The user and the moderators could respond with a specific command (maybe `!close` in that specific channel or DM) to close the case as needed.  I have attached screenshots of how it might look as an initial, with viewpoints from both the user and the channel:
![screen shot on 2018-02-27 at 12_45_58](https://user-images.githubusercontent.com/27379200/36748025-46a38c9a-1bbc-11e8-88f4-c343059b7a96.png)
![screen shot on 2018-02-27 at 12_46_25](https://user-images.githubusercontent.com/27379200/36748028-48a5885e-1bbc-11e8-967e-39562a721b96.png)

Obviously there would be more detail than those screenshots, that is merely showcasing the concept.  Overall this feature could be used anywhere from contacting a moderator to report a user DMing invites or other issues of abuse to being turned into some form of ticket support system.

**Comment by HaydenMeloche** [comment]
So, would this create a new text channel every for every case?

**Comment by coledeb** [comment]
Fully dependent on how we would want to handle it, but I would suggest having one channel and the bot creating cases in that one channel one at a time based on the order that it came in.  Obviously I'm kind of talking just conceptually as I don't have the slightest idea of the capabilities provided to bots from discord, but smart 1 by 1 handling of the cases would be better. If that *is* possible, perhaps telling the user that their case is in a waiting list and then DMing them the "message has been sent" message upon closure of the case opened prior

**Comment by coledeb** [comment]
Yup I remember talking about this @ThePjpollie , I just wanted to write it down on here so it didn't get lost within our DMs or other channels.

**Comment by coledeb** [comment]
https://github.com/dragory/modmailbot

Here is another example of a modmail functionality, I believe the overwatch server's mod mail is done through this. @ThePjpollie @HaydenMeloche

**Comment by coledeb** [comment]
An update on this, the RL subreddit discord has also debuted a mod mail bot. Seems to be a popular idea

**Comment by ThePjpollie** [comment]
Alright, how I'm planning to do it:

Users can DM the bot with: `!question <question of the user here>`.
There will be a channel called `#mod-mail` where it'll post the question in there with the question ID.
To answer the question you can do `!a <question id> <answer>`.

*Why do people typ `!question` to ask a question. Why not straight up accept all DM questions?*
If I'm correct Root has logged every DM once and A LOT of those were like `!set title` commands are unrelatable stuff. So if you dont want the mod-mail to be flooded with this then I would suggest using this.

*Why do I need to do `!a <id>` before answering?*
Well I could do without, but what about 2 users asking smth at the same time. You can't answer the first one anymore. Or how can the bot know?

*Why don't you make a channel for every question?*
I could... But don't you think it'll be quite a mess?

I am thinking of making it once you do !question it'll also send the mods all the rest of the messages sent through DM until the case is closed. From then on they need to do !question again to start a new one.

I am open for other ideas or open to learn on how RL Subreddits version work. 
Just how I see it :)
