### ISSUE TITLE
!update command for bot

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#25]
The bot needs to have an `!update` command that updates the bot, during which it blocks `#set-title`, `#set-special-title`, `#showcase`, and `#suggestions` from being able to be typed in besides admins and devs. Once it updates, it reopens these channels. The bot gives a response in `#the-basement` (Or `#development`, whatever you want @HaydenMeloche) whenever it is back online.

**Comment by ThePjpollie** [comment]
Does this still need to be open? Is there anything missing in this yet?

**Comment by HaydenMeloche** [comment]
Nope. my bad. @ThePjpollie
