### ISSUE TITLE
!lastseen command

### ISSUE THREAD

**Issue by burnss9** [HaydenMeloche/AlphaConsoleBot#65]
add a last seen command that will return either how long its been or what the date/time was when they were last seen. (found in the title db)

preferably lookup for discord and steam potentially using !lastseen steam id or !lastseen discord id/tag or just one command that takes either 🤷‍♀️

**Comment by ThePjpollie** [comment]
@HaydenMeloche I'll leave the `last seen. (found in the title db)` over to you?
That's as far as I know not in the sqlite db and I'm not used to it so don't wanna mess with it.

I could add the discord last message thing afterwards :)

**Comment by HaydenMeloche** [comment]
Sounds good
