### ISSUE TITLE
Changing Nickname also returns Role change in #server-log

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#73]
I changed my nickname from `Cole` to `Cole.` to test how it would look in `#server-log` and when I changed it (and also when I changed it back) it returned that I had added or removed a role as well (I didn't.)

![6d38d7c614ef778da8d3e52aab5e6b07](https://user-images.githubusercontent.com/27379200/34645996-5734d478-f322-11e7-98be-04e779d5d9d3.png)

**Comment by HaydenMeloche** [comment]
Merged in #75
