### ISSUE TITLE
If user gets role 'Twitch Sub'

### ISSUE THREAD

**Issue by HaydenMeloche** [HaydenMeloche/AlphaConsoleBot#84]
If a user receives the role `Twitch Sub`. Notify them that they have it and tell them what features they now have.

**Comment by ThePjpollie** [comment]
Could you post the text here what it should tell them? In case I'm gonna look into it I don't have to wait for the text :)

**Comment by coledeb** [comment]
Thank you for subscribing to our twitch! :smile: you now have access to several benefits including:

Green & Purple title colors
The `AlphaConsole Twitch Sub` special title (found in `#set-special-title`)
Our beta program (Please read `#beta-info` and the pin in `#beta-steam-ids` carefully!)
The `#subs-and-legacy` text channel and priority support
Various Discord server enhancements such as nickname perms

You will keep these benefits for as long as you are subscribed, and you will have a 3 day window to resubscribe if your subscription runs out. Thank you again for your subscription, and your extra level of support for AlphaConsole!
