### ISSUE TITLE
!status enhancements

### ISSUE THREAD

**Issue by coledeb** [HaydenMeloche/AlphaConsoleBot#85]
If possible, it would be cool to have the status automatically update when someone is actually streaming on the channel to be `STREAMING @ .tv/AlphaConsole` . Whenever someone is streaming, this status would take over the current statuses until the streamer is done streaming.

Also, having the current member count that is shown when the bot does not have a status added in as an automatic (permanent) status to rotate through would be good as well, rather than only being an option when there are no statuses set.

**Comment by ThePjpollie** [comment]
```
If possible, it would be cool to have the status automatically update when someone is actually streaming on the channel to be STREAMING @ .tv/AlphaConsole . Whenever someone is streaming, this status would take over the current statuses until the streamer is done streaming.
```

Right now it has on **every** cycle you do the twitch linked to the status. So if I'm not mistaken once live it'll automatically switch to STREAMING with the title of the stream as the rest of the status + a WATCH NOW button to go to the stream

**Comment by ThePjpollie** [comment]
Will keep this open until a stream has happened and we can confirm this stream works

**Comment by ThePjpollie** [comment]
Not fully fixed. Cole added status, not showing any status right now.
Probably due to `@`

**Comment by ThePjpollie** [comment]
Since it's now a duplicate with #150 I'll be closing this one
